In [2]:
import pandas as pd

In [4]:
atmiya = pd.read_csv("final aatmiya realty.csv")
atmiya

,Pdf No,Bill no,Name,Party Name,Invoice no,Bill Date,Paid Date,Purchase Voucher,General Voucher,Material Code,Qty,Unit,Basic Amount,GST,VAT,TDS,Total,Company Name,PDF URL
0,1,1446,Darshan,DOSHI INC,1106,28-01-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,15513,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/1...
1,1,0,Darshan,DOSHI INC,0,02-08-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,10744,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/2...
2,1,0,Darshan,DOSHI INC,0,02-08-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,10841,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/3...
3,1,1555,Darshan,CERAMICA GALAXY,637,22-02-2014,NaN,NaN,NaN,ACC BLOCK,NaN,NaN,74175,NaN,2764,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/4...
4,1,1444,Darshan,TOP BRICKS,1,31-01-2014,NaN,NaN,NaN,BRICKS MATERIAL,79961,no,103950,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6713,50,NaN,SUDHIR,SPEED ELEVATORS,392,31-03-2021,NaN,NaN,NaN,NaN,NaN,NaN,2773,NaN,0,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/50/...
6714,50,NaN,SUDHIR,SPEED ELEVATORS,385,31-03-2021,NaN,NaN,NaN,NaN,NaN,NaN,7080,NaN,0,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/50/...
6715,50,NaN,SUDHIR,SPEED ELEVATORS,386,31-03-2021,NaN,NaN,NaN,NaN,NaN,NaN,1062,NaN,0,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/50/...
6716,50,NaN,SUDHIR,SPEED ELEVATORS,315,31-03-2021,NaN,NaN,NaN,NaN,NaN,NaN,2950,NaN,0,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/50/...
6717,50,NaN,SUDHIR,SPEED ELEVATORS,320,31-03-2015,NaN,NaN,NaN,NaN,NaN,NaN,1003,NaN,0,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/50/...

In [5]:
atmiya.columns

Index(['Pdf No', 'Bill no', 'Name', 'Party Name', 'Invoice no', 'Bill Date',
       'Paid Date', 'Purchase Voucher', 'General Voucher', 'Material Code',
       'Qty', 'Unit', 'Basic Amount', 'GST', 'VAT', 'TDS', 'Total',
       'Company Name', 'PDF URL'],
      dtype='object')

In [8]:
atmiya['Name'].dtypes

dtype('O')

In [10]:

a = pd.DataFrame(atmiya)
print(a.dtypes)

Pdf No               object
Bill no              object
Name                 object
Party Name           object
Invoice no           object
Bill Date            object
Paid Date           float64
Purchase Voucher    float64
General Voucher     float64
Material Code        object
Qty                  object
Unit                 object
Basic Amount         object
GST                 float64
VAT                  object
TDS                  object
Total                object
Company Name         object
PDF URL              object
dtype: object

In [17]:
    atmiya[atmiya["Name"] == "Darshan"]

,Pdf No,Bill no,Name,Party Name,Invoice no,Bill Date,Paid Date,Purchase Voucher,General Voucher,Material Code,Qty,Unit,Basic Amount,GST,VAT,TDS,Total,Company Name,PDF URL
0,1,1446,Darshan,DOSHI INC,1106,28-01-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,15513,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/1...
1,1,0,Darshan,DOSHI INC,0,02-08-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,10744,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/2...
2,1,0,Darshan,DOSHI INC,0,02-08-2014,NaN,NaN,NaN,PLAMBING MATERIAL,NaN,NaN,10841,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/3...
3,1,1555,Darshan,CERAMICA GALAXY,637,22-02-2014,NaN,NaN,NaN,ACC BLOCK,NaN,NaN,74175,NaN,2764,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/4...
4,1,1444,Darshan,TOP BRICKS,1,31-01-2014,NaN,NaN,NaN,BRICKS MATERIAL,79961,no,103950,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/1/5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,1/1900,0,Darshan,JAGDISH YADAV,0,26-05-2018,NaN,NaN,NaN,NaN,NaN,NaN,8750,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/9/1...
1049,1/1900,0,Darshan,ADITYA COROPORATION,441,26-05-2018,NaN,NaN,NaN,NaN,40,case,8496,NaN,1290,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/9/1...
1050,1/1900,6852,Darshan,SHEETAL PAPER MART,190,11-04-2018,NaN,NaN,NaN,OFFICE EXPENCE,NaN,NaN,2080,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/9/1...
1051,1/1900,0,Darshan,GUJARAT ENTERPRISE,202,28-04-2018,NaN,NaN,NaN,NaN,NaN,NaN,11337,NaN,NaN,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/9/1...
1052,1/1900,0,Darshan,MANUSHI ENTERPRISE,160,07-12-2017,NaN,NaN,NaN,HARDWARE MATERIAL,NaN,NaN,4366,NaN,666,NaN,NaN,Aatmiya Realty,upload/billing_document/pdf/aatmiya_realty/9/1...